name: GitHub Actions
run-name: Running necessary checks 🚀
on: [push]
jobs:
  Code-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v6.0.3
      - name: 🚚 Installing dependencies
        run: pnpm install
      - name: 🏷️ running typecheck
        run: pnpm build
      - name: 🧪 Running tests
        run: pnpm test
      - name: 🚨 Linting code
        run: pnpm lint
      - name: 🚨 prettier check code
        run: pnpm format:check
